server:
  port: 7777
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: eddi@123
    key-store-type: PKCS12


spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/coffee_ground?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    url: jdbc:mysql://mysql-container/coffee_ground?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: eddi
    password: eddi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis

  redis:
    host: 127.0.0.1
    port: 6379
    username: default
    password: eddi@123


  # OAuth 로그인
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5801ca2cc4aa7e73a60cb2228ec68cfc
            client-secret: 2f05q3PZfC8WuHxNhC6a4FUgCMRTYNXe
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

#          naver:
#            client-id: 발급받은 Client ID
#            client-secret: 발급받은 Client Secret
#            scope:
#              - name
#              - email
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
